// https://ksp-kos.github.io/KOS/commands/flight/cooked.html


SET STEERINGMANAGER:MAXSTOPPINGTIME TO 20.
SET STEERINGMANAGER:PITCHPID:KD TO 1.
SET STEERINGMANAGER:YAWPID:KD TO 1.
SET STEERINGMANAGER:ROLLPID:KD TO 1.
SET STEERINGMANAGER:PITCHTS TO 10.
SET STEERINGMANAGER:YAWTS TO 10.