


IF SHIP:STATUS = "PRELAUNCH" {

    SET STEERINGMANAGER:MAXSTOPPINGTIME TO 10.
    SET STEERINGMANAGER:PITCHPID:KD TO 1.
    SET STEERINGMANAGER:YAWPID:KD TO 1.
    SET STEERINGMANAGER:ROLLPID:KD TO 1.

    RUN launch_asc(200000). // Launches to 200km

    WAIT 5.

    RUN DEORBITSP(0).
}